scrape_configs:
- job_name: prometheus
  scrape_interval: 15s
  scrape_timeout: 10s
  metrics_path: /metrics
  scheme: http
  static_configs:
  - targets:
    - localhost:9090

- job_name: class
  static_configs:
  - targets:
    - 192.168.15.101:3000

- job_name: server-001
  static_configs:
  - targets:
    - 3.87.217.36:9100    